// svelte4/bind/src/routes/bind-input/ui/Parent.svelte
<!-- Parent.svelte -->
<script lang="ts">
  import Child from './Child.svelte'

  let name: string = 'John Doe'

  function updateName (event: CustomEvent<string>) {
    name = event.detail
  }
</script>

<h1>Parent Component</h1>
<p>Parent Name: {name}</p>

<Child bind:value={name} on:update={updateName} />

// vue3/two-way-binding-aka-v-model/src/components/simple/Parent.vue
<script setup lang="ts">
import { ref } from 'vue'

import Child from './Child.vue'

const countModel = ref(0)
</script>

<template>
  <div>
    <p>Parent bound modelValue is: {{ countModel }}</p>
    <Child
      :modelValue="countModel"
      @update:modelValue="countModel = $event"
    />
  </div>
</template>
